modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/AlexModGuy/AlexsCaves/issues" #optional
[[mods]] #mandatory
modId="alexscaves" #mandatory
version="2.0.2" #mandatory
displayName="Alex's Caves" #mandatory
displayURL="" #optional
authors="Alexthe668, Noonyeyz" #optional
credits="LudoCrypt, _Ninni, PrismaticPinky, RenRen, Gatetoh, arby698, PlummetStudios, HolidayRaptor" #optional
description='''Explore new rare cave biomes hidden under the surface of the Overworld...'''
logoFile="assets/alexscaves/textures/misc/mod_logo.png" #optional
[[dependencies.alexscaves]] #optional
# the modid of the dependency
modId="citadel" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[2.6.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.alexscaves]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"